/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.core.banking.view;

import com.core.banking.model.Credit;
import com.core.banking.model.ResponseModel;
import com.core.banking.service.impl.CreditServiceImpl;
import com.core.banking.session.CustomerSession;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Murat
 */
public class Admin_CreditApproval extends javax.swing.JFrame {

    private CreditServiceImpl creditService=new CreditServiceImpl();
    private List<Credit> creditList=new ArrayList<>();
    
    /**
     * Creates new form Admin_CreditApproval
     */
    public Admin_CreditApproval() {
        initComponents();
    
        ResponseModel<List<Credit>> responsemodel3=creditService.kayıtlıBasvurular();
        if(responsemodel3.isSuccess()){
            creditList=responsemodel3.getResponseObject();
            for(Credit credit : creditList){
                appealsComboBox.addItem(String.valueOf(credit.getId()));
            }
                
        }else{
        
        
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appealsComboBox = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        appealApprove = new javax.swing.JButton();
        appealDeny = new javax.swing.JButton();
        nameSurname = new javax.swing.JTextField();
        creditAmount = new javax.swing.JTextField();
        customerNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appealsComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                appealsComboBoxİtemStateChanged(evt);
            }
        });

        back.setText("GERİ");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        appealApprove.setText("BAŞVURUYU ONAYLA");
        appealApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appealApproveActionPerformed(evt);
            }
        });

        appealDeny.setText("BAŞVURUYU REDDET");
        appealDeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appealDenyActionPerformed(evt);
            }
        });

        nameSurname.setEditable(false);

        creditAmount.setEditable(false);

        customerNumber.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(appealsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appealDeny)
                    .addComponent(appealApprove))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameSurname)
                    .addComponent(creditAmount)
                    .addComponent(customerNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(appealsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(creditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(customerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(appealApprove)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(appealDeny))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appealsComboBoxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_appealsComboBoxİtemStateChanged
        int index = appealsComboBox.getSelectedIndex();
        Credit credit = creditList.get(index);
        nameSurname.setText(credit.getCustomer().getName()+" "+credit.getCustomer().getSurname());
        creditAmount.setText(String.valueOf(credit.getMainAmount()));
        customerNumber.setText(String.valueOf(credit.getCustomer().getCustomerNumber()));    
    }//GEN-LAST:event_appealsComboBoxİtemStateChanged

    private void appealDenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appealDenyActionPerformed
        ResponseModel<Boolean> responsemodel=creditService.basvuruReddi(creditList.get(appealsComboBox.getSelectedIndex()).getId());
        if(responsemodel.isSuccess()){
            JOptionPane.showMessageDialog(rootPane, responsemodel.getMessage());
        }else{
            JOptionPane.showMessageDialog(rootPane, responsemodel.getMessage());
        }
    }//GEN-LAST:event_appealDenyActionPerformed

    private void appealApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appealApproveActionPerformed
        ResponseModel<Boolean> responsemodel=creditService.basvuruOnayla(creditList.get(appealsComboBox.getSelectedIndex()).getId());
        if(responsemodel.isSuccess()){
            JOptionPane.showMessageDialog(rootPane, responsemodel.getMessage());
        }else{
            JOptionPane.showMessageDialog(rootPane, responsemodel.getMessage());
        }
    }//GEN-LAST:event_appealApproveActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        CustomerSession.getParentFrame().get(CustomerSession.getParentFrame().size()-1).setVisible(true);
        CustomerSession.getParentFrame().remove(CustomerSession.getParentFrame().size()-1);
        this.setVisible(false);      
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_CreditApproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_CreditApproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_CreditApproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_CreditApproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_CreditApproval().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appealApprove;
    private javax.swing.JButton appealDeny;
    private javax.swing.JComboBox<String> appealsComboBox;
    private javax.swing.JButton back;
    private javax.swing.JTextField creditAmount;
    private javax.swing.JTextField customerNumber;
    private javax.swing.JTextField nameSurname;
    // End of variables declaration//GEN-END:variables
}
