/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.core.banking.view;

import com.core.banking.model.Account;
import com.core.banking.model.CreditCard;
import com.core.banking.model.Invoice;
import com.core.banking.model.ResponseModel;
import com.core.banking.service.impl.AccountServiceImpl;
import com.core.banking.service.impl.CreditCardServiceImpl;
import com.core.banking.service.impl.InvoiceServiceImpl;
import com.core.banking.session.CustomerSession;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Murat
 */
public class ATM_InvoicePayment extends javax.swing.JFrame {

    private InvoiceServiceImpl invoiceService=new InvoiceServiceImpl();
    private List<Invoice> list = new ArrayList<>();
    private AccountServiceImpl accountService=new AccountServiceImpl();
    private List<Account> accountList = new ArrayList<>();
    private CreditCardServiceImpl creditCardService=new CreditCardServiceImpl();
    private List<CreditCard> creditCardList=new ArrayList<>();
    
    public ATM_InvoicePayment() {
        initComponents();
        creditCardsComboBox.setVisible(false);
        accountsComboBox.setVisible(false);
    
        ResponseModel<List<Invoice>> responsemodel = invoiceService.kayıtlıFaturalar();
        if(responsemodel.isSuccess()){
            list = responsemodel.getResponseObject();
            for(Invoice invoice : list){
                invoiceComboBox.addItem(invoice.getInvoiceNo()+"");
            }
        }else{
          
        
        }
        
        ResponseModel<List<Account>> responsemodel2 = accountService.kayıtlıHesaplar();
        if(responsemodel2.isSuccess()){
            accountList = responsemodel2.getResponseObject();
            for(Account account : accountList){
                accountsComboBox.addItem(account.getName());
            }
        }else{
            //jComboBox1.addItem("Hesap Bulunamadı!");
        
        }                                
        
        ResponseModel<List<CreditCard>> responsemodel3=creditCardService.kayıtlıKartlar();
        if(responsemodel3.isSuccess()){
            creditCardList=responsemodel3.getResponseObject();
            for(CreditCard creditCard : creditCardList){
                creditCardsComboBox.addItem(creditCard.getCardNumber());
            }
                
        }else{
        
        
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        invoiceComboBox = new javax.swing.JComboBox<>();
        confirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        debt = new javax.swing.JTextField();
        creditCardButton = new javax.swing.JRadioButton();
        accountButton = new javax.swing.JRadioButton();
        accountsComboBox = new javax.swing.JComboBox<>();
        creditCardsComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setText("GERİ");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setText("Ödemek istediğiniz faturayı ve ödeme yönteminizi seçiniz.");

        invoiceComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                invoiceComboBoxİtemStateChanged(evt);
            }
        });

        confirm.setText("ONAYLA");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        jLabel2.setText("Fatura tutarı:");

        debt.setEditable(false);

        buttonGroup1.add(creditCardButton);
        creditCardButton.setText("KREDİ KARTI");
        creditCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(accountButton);
        accountButton.setText("BANKA HESABI");
        accountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButtonActionPerformed(evt);
            }
        });

        creditCardsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardsComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirm)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(debt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(accountButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(invoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170)
                                .addComponent(creditCardButton)
                                .addGap(0, 12, Short.MAX_VALUE)))
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(accountsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(creditCardsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardButton)
                    .addComponent(invoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditCardsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accountButton)
                .addGap(9, 9, 9)
                .addComponent(accountsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(debt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(confirm))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        CustomerSession.getParentFrame().get(CustomerSession.getParentFrame().size()-1).setVisible(true);
        CustomerSession.getParentFrame().remove(CustomerSession.getParentFrame().size()-1);
        this.setVisible(false);      
    }//GEN-LAST:event_backActionPerformed

    private void invoiceComboBoxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_invoiceComboBoxİtemStateChanged
        int index = invoiceComboBox.getSelectedIndex();
        Invoice invoice = list.get(index);
        debt.setText(invoice.getAmount()+"");
    }//GEN-LAST:event_invoiceComboBoxİtemStateChanged

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        if(accountButton.isSelected()){            
            ResponseModel<Invoice> responsemodel4=invoiceService.hesaptanFaturaOdeme(list.get(invoiceComboBox.getSelectedIndex()), accountList.get(accountsComboBox.getSelectedIndex()));
            if(responsemodel4.isSuccess()){                                                
                JOptionPane.showMessageDialog(rootPane, responsemodel4.getMessage());
            
            }else{
                JOptionPane.showMessageDialog(rootPane, responsemodel4.getMessage());  
            }
            
        }else if(creditCardButton.isSelected()){
            ResponseModel<Invoice> responsemodel4=invoiceService.karttanFaturaOdeme(list.get(invoiceComboBox.getSelectedIndex()), creditCardList.get(creditCardsComboBox.getSelectedIndex()));
            if(responsemodel4.isSuccess()){
                JOptionPane.showMessageDialog(rootPane, responsemodel4.getMessage());
            }else{
                JOptionPane.showMessageDialog(rootPane, responsemodel4.getMessage());
            }
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void creditCardsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardsComboBoxActionPerformed
        
    }//GEN-LAST:event_creditCardsComboBoxActionPerformed

    private void creditCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardButtonActionPerformed
        creditCardsComboBox.setVisible(true);
        accountsComboBox.setVisible(false);
    }//GEN-LAST:event_creditCardButtonActionPerformed

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        creditCardsComboBox.setVisible(false);
        accountsComboBox.setVisible(true);
    }//GEN-LAST:event_accountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM_InvoicePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM_InvoicePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM_InvoicePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM_InvoicePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM_InvoicePayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton accountButton;
    private javax.swing.JComboBox<String> accountsComboBox;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton confirm;
    private javax.swing.JRadioButton creditCardButton;
    private javax.swing.JComboBox<String> creditCardsComboBox;
    private javax.swing.JTextField debt;
    private javax.swing.JComboBox<String> invoiceComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
